const roomData = [
  {
    number: 1,
    roomType: 'residential suite',
    bidet: 'true',
    bedSize: 'queen',
    numBeds: 1,
    costPerNight: 1268.8,
  },
  {
    number: 2,
    roomType: 'suite',
    bidet: 'false',
    bedSize: 'Full',
    numBeds: 2,
    costPerNight: 1358.04,
  },
  {
    number: 3,
    roomType: 'single room',
    bidet: 'false',
    bedSize: 'king',
    numBeds: 1,
    costPerNight: 1368.36,
  },
  {
    number: 4,
    roomType: 'single room',
    bidet: 'false',
    bedSize: 'queen',
    numBeds: 1,
    costPerNight: 1322.08,
  },
  {
    number: 5,
    roomType: 'single room',
    bidet: 'true',
    bedSize: 'queen',
    numBeds: 2,
    costPerNight: 1255.13,
  },
  {
    number: 6,
    roomType: 'junior Suite',
    bidet: 'true',
    bedSize: 'queen',
    numBeds: 1,
    costPerNight: 1297.77,
  },
  {
    number: 7,
    roomType: 'single room',
    bidet: 'false',
    bedSize: 'queen',
    numBeds: 2,
    costPerNight: 1173.6,
  },
  {
    number: 8,
    roomType: 'junior Suite',
    bidet: 'false',
    bedSize: 'king',
    numBeds: 1,
    costPerNight: 1195.95,
  },
  {
    number: 9,
    roomType: 'single room',
    bidet: 'true',
    bedSize: 'queen',
    numBeds: 1,
    costPerNight: 1150.29,
  },
  {
    number: 10,
    roomType: 'suite',
    bidet: 'false',
    bedSize: 'Twin',
    numBeds: 1,
    costPerNight: 1373.23,
  },
  {
    number: 11,
    roomType: 'single room',
    bidet: 'true',
    bedSize: 'twin',
    numBeds: 2,
    costPerNight: 1155.43,
  },
  {
    number: 12,
    roomType: 'single room',
    bidet: 'false',
    bedSize: 'twin',
    numBeds: 2,
    costPerNight: 1129.07,
  },
  {
    number: 13,
    roomType: 'single room',
    bidet: 'false',
    bedSize: 'queen',
    numBeds: 2,
    costPerNight: 1317.94,
  },
  {
    number: 14,
    roomType: 'residential suite',
    bidet: 'false',
    bedSize: 'twin',
    numBeds: 1,
    costPerNight: 1343.41,
  },
  {
    number: 15,
    roomType: 'residential suite',
    bidet: 'false',
    bedSize: 'full',
    numBeds: 1,
    costPerNight: 1220.92,
  },
  {
    number: 16,
    roomType: 'single room',
    bidet: 'false',
    bedSize: 'full',
    numBeds: 2,
    costPerNight: 1244.2,
  },
  {
    number: 17,
    roomType: 'junior Suite',
    bidet: 'false',
    bedSize: 'twin',
    numBeds: 2,
    costPerNight: 1246.11,
  },
  {
    number: 18,
    roomType: 'junior suite',
    bidet: 'false',
    bedSize: 'king',
    numBeds: 2,
    costPerNight: 1372.31,
  },
  {
    number: 19,
    roomType: 'single room',
    bidet: 'false',
    bedSize: 'queen',
    numBeds: 1,
    costPerNight: 1281,
  },
  {
    number: 20,
    roomType: 'residential suite',
    bidet: 'false',
    bedSize: 'queen',
    numBeds: 1,
    costPerNight: 1257.96,
  },
  {
    number: 21,
    roomType: 'single room',
    bidet: 'false',
    bedSize: 'full',
    numBeds: 2,
    costPerNight: 1321.99,
  },
  {
    number: 22,
    roomType: 'single room',
    bidet: 'false',
    bedSize: 'full',
    numBeds: 2,
    costPerNight: 1262.73,
  },
  {
    number: 23,
    roomType: 'residential suite',
    bidet: 'false',
    bedSize: 'queen',
    numBeds: 2,
    costPerNight: 1132.27,
  },
  {
    number: 24,
    roomType: 'suite',
    bidet: 'false',
    bedSize: 'queen',
    numBeds: 1,
    costPerNight: 1245.43,
  },
  {
    number: 25,
    roomType: 'single room',
    bidet: 'true',
    bedSize: 'queen',
    numBeds: 1,
    costPerNight: 1229.39,
  },
];

export default roomData;
